apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cocola-plugins
  labels:
    app.kubernetes.io/name: cocola-plugins
    app.kubernetes.io/part-of: cocola
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
