export const LOCAL_SIMPLE_ICON_PATHS: Record<string, string> = {
  anthropic: "/brands/anthropic.svg",
  claude: "/brands/claude.svg",
  claudecode: "/api/model-icons/claudecode",
  openai: "/brands/openai.svg",
  codex: "/api/model-icons/codex",
  deepseek: "/brands/deepseek.svg",
  qwen: "/brands/qwen.svg",
  google: "/brands/google.svg",
  googlegemini: "/brands/googlegemini.svg",
  gemini: "/api/model-icons/gemini",
  xai: "/api/model-icons/xai",
  grok: "/api/model-icons/grok",
  mistral: "/api/model-icons/mistral",
  metaai: "/api/model-icons/metaai",
  cohere: "/api/model-icons/cohere",
  groq: "/api/model-icons/groq",
  perplexity: "/api/model-icons/perplexity",
  moonshot: "/api/model-icons/moonshot",
  kimi: "/api/model-icons/kimi",
  doubao: "/api/model-icons/doubao",
  volcengine: "/api/model-icons/volcengine",
  zhipu: "/api/model-icons/zhipu",
  chatglm: "/api/model-icons/chatglm",
  baiducloud: "/api/model-icons/baiducloud",
  wenxin: "/api/model-icons/wenxin",
  minimax: "/api/model-icons/minimax",
  stepfun: "/api/model-icons/stepfun",
  zeroone: "/api/model-icons/zeroone",
  baichuan: "/api/model-icons/baichuan",
  openrouter: "/api/model-icons/openrouter",
  ollama: "/api/model-icons/ollama",
  azureai: "/api/model-icons/azureai",
  bedrock: "/api/model-icons/bedrock",
  nvidia: "/api/model-icons/nvidia",
  huggingface: "/api/model-icons/huggingface",
  siliconcloud: "/api/model-icons/siliconcloud",
  together: "/api/model-icons/together",
  fireworks: "/api/model-icons/fireworks",
  cerebras: "/api/model-icons/cerebras",
  sambanova: "/api/model-icons/sambanova",
  replicate: "/api/model-icons/replicate",
};

export const SIMPLE_ICON_SLUGS = Object.keys(LOCAL_SIMPLE_ICON_PATHS);

export const SIMPLE_ICON_LABELS: Record<string, string> = {
  anthropic: "Anthropic",
  claude: "Claude",
  claudecode: "Claude Code",
  openai: "OpenAI",
  codex: "OpenAI Codex",
  deepseek: "DeepSeek",
  qwen: "Qwen",
  google: "Google",
  googlegemini: "Google Gemini",
  gemini: "Gemini",
  xai: "xAI",
  grok: "Grok",
  mistral: "Mistral AI",
  metaai: "Meta AI",
  cohere: "Cohere",
  groq: "Groq",
  perplexity: "Perplexity",
  moonshot: "Moonshot",
  kimi: "Kimi",
  doubao: "Doubao",
  volcengine: "Volcengine",
  zhipu: "Zhipu AI",
  chatglm: "ChatGLM",
  baiducloud: "Baidu AI Cloud",
  wenxin: "ERNIE / Wenxin",
  minimax: "MiniMax",
  stepfun: "StepFun",
  zeroone: "01.AI",
  baichuan: "Baichuan AI",
  openrouter: "OpenRouter",
  ollama: "Ollama",
  azureai: "Azure AI",
  bedrock: "Amazon Bedrock",
  nvidia: "NVIDIA",
  huggingface: "Hugging Face",
  siliconcloud: "SiliconCloud",
  together: "Together AI",
  fireworks: "Fireworks AI",
  cerebras: "Cerebras",
  sambanova: "SambaNova",
  replicate: "Replicate",
};

export const SIMPLE_ICON_FALLBACK_BADGES: Record<string, string> = {
  anthropic: "A",
  claude: "C",
  claudecode: "CC",
  openai: "AI",
  codex: "CX",
  deepseek: "DS",
  qwen: "Q",
  google: "G",
  googlegemini: "G",
  gemini: "G",
  xai: "xAI",
  grok: "G",
  mistral: "M",
  metaai: "M",
  cohere: "C",
  groq: "GQ",
  perplexity: "P",
  moonshot: "K",
  kimi: "K",
  doubao: "D",
  volcengine: "V",
  zhipu: "Z",
  chatglm: "GL",
  baiducloud: "B",
  wenxin: "W",
  minimax: "MM",
  stepfun: "S",
  zeroone: "01",
  baichuan: "BC",
  openrouter: "OR",
  ollama: "O",
  azureai: "AZ",
  bedrock: "AWS",
  nvidia: "NV",
  huggingface: "HF",
  siliconcloud: "SC",
  together: "T",
  fireworks: "FW",
  cerebras: "CB",
  sambanova: "SN",
  replicate: "R",
};

export const LOBE_ICON_SLUG_ALIASES: Record<string, string> = {
  anthropic: "anthropic",
  claude: "claude",
  claudecode: "claudecode",
  codex: "codex",
  deepseek: "deepseek",
  doubao: "doubao",
  gemini: "gemini",
  google: "google",
  googlegemini: "gemini",
  meta: "metaai",
  metaai: "metaai",
  grok: "grok",
  kimi: "kimi",
  mistral: "mistral",
  moonshot: "moonshot",
  openai: "openai",
  qwen: "qwen",
  volcengine: "volcengine",
  xai: "xai",
};

export function normalizeLobeIconSlug(slug: string | undefined): string {
  const normalized = (slug ?? "").trim().toLowerCase().replace(/_/g, "-");
  if (!/^[a-z0-9-]+$/.test(normalized)) return "";
  return LOBE_ICON_SLUG_ALIASES[normalized] ?? normalized;
}

export function lobeIconPath(slug: string | undefined): string {
  const normalized = normalizeLobeIconSlug(slug);
  return normalized ? `/api/model-icons/${normalized}` : "";
}
