// Code generated by scripts/generate_third_party_images.py; DO NOT EDIT.

package config

const (
	redisTargetImage             = "ghcr.io/sakurs2/cocola-redis"
	redisVersion                 = "7.4.10-alpine3.21"
	redisManifestDigest          = "sha256:e7723ff73d963f5cc6d9c4643ea3d989527a402a319239054e9472a7fb9219a2"
	postgresTargetImage          = "ghcr.io/sakurs2/cocola-postgres"
	postgresVersion              = "16.14-alpine3.23"
	postgresManifestDigest       = "sha256:42b8b8b29c8a4e933d88943e5b03001a78794905cf786e6e7634e9f2abd5a0d3"
	forgejoTargetImage           = "ghcr.io/sakurs2/cocola-forgejo"
	forgejoVersion               = "16.0.1"
	forgejoManifestDigest        = "sha256:3eb3107bc9de4e9d6d9e539044e6c802dc0b7be351919a145540d4cb5422bf07"
	minioTargetImage             = "ghcr.io/sakurs2/cocola-minio"
	minioVersion                 = "RELEASE.2025-09-07T16-13-09Z"
	minioManifestDigest          = "sha256:14cea493d9a34af32f524e538b8346cf79f3321eff8e708c1e2960462bd8936e"
	minioClientTargetImage       = "ghcr.io/sakurs2/cocola-minio-mc"
	minioClientVersion           = "RELEASE.2025-08-13T08-35-41Z"
	minioClientManifestDigest    = "sha256:a7fe349ef4bd8521fb8497f55c6042871b2ae640607cf99d9bede5e9bdf11727"
	openVikingTargetImage        = "ghcr.io/volcengine/openviking"
	openVikingVersion            = "v0.4.12"
	openVikingDigest             = "sha256:0d99361a0029ce5221fd11588d9f0f374c6e5f8f1eacbcf1d76de6a0f6cd82cb"
	openSandboxServerTargetImage = "ghcr.io/sakurs2/cocola-opensandbox-server"
	openSandboxServerVersion     = "v0.1.14"
	openSandboxServerDigest      = "sha256:a177a0fd149dcf4035d884590cabd78021b7baa63782830647a8eb9c663d176a"
	openSandboxEgressTargetImage = "ghcr.io/sakurs2/cocola-opensandbox-egress"
	openSandboxEgressVersion     = "v1.1.2"
	openSandboxEgressDigest      = "sha256:c3944a6dd060638c89ef9526ddea34f98192b987e13e3b7fe5e8b4606126b3cf"
)
