apiVersion: v1
kind: ServiceAccount
metadata:
  name: sandbox-manager
  namespace: {{ .Values.namespaces.controlPlane }}
  labels:
    {{- include "cocola-sandbox.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-manager
  namespace: {{ .Values.namespaces.sandboxes }}
  labels:
    {{- include "cocola-sandbox.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods", "persistentvolumeclaims", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-manager
  namespace: {{ .Values.namespaces.sandboxes }}
  labels:
    {{- include "cocola-sandbox.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: sandbox-manager
    namespace: {{ .Values.namespaces.controlPlane }}
roleRef:
  kind: Role
  name: sandbox-manager
  apiGroup: rbac.authorization.k8s.io
