{{- if .Values.sandbox.pluginsPVC.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.sandbox.pluginsPVC.name }}
  namespace: {{ .Values.namespaces.sandboxes }}
  labels:
    {{- include "cocola-sandbox.labels" . | nindent 4 }}
    cocola.bytedance.com/managed: "true"
spec:
  accessModes: ["ReadOnlyMany"]
  resources:
    requests:
      storage: {{ .Values.sandbox.pluginsPVC.size }}
  {{- with .Values.sandbox.pluginsPVC.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
{{- end }}
{{- if .Values.sandbox.defaultDenyEgress }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cocola-default-deny-egress
  namespace: {{ .Values.namespaces.sandboxes }}
  labels:
    {{- include "cocola-sandbox.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: ["Egress"]
{{- end }}
